# Site settings
title: cloud.gov
description: "cloud.gov is a Platform-as-a-Service based on Cloud Foundry offered by 18F Infrastructure enabling agile teams to deploy software as fast as they can iterate."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cloud.18f.gov" # the base hostname & protocol for your site
logo: /assets/img/cloudgov.png
feature_image: /assets/img/feature-background.jpg

colors:
  background: '#ffffff'
  button:
    background: '#0071bc'
    hover: '#3e94cf'
    text: '#fff'
  headers: '#205493'
  text: '#212121'
  projects:
    accent: '#02bfe7'
  banner:
    background: '#112e51'
    text: '#fff'
    button:
      background: '#dce4ef'
      text: '#112e51'
  footer:
    background: '#323a45'
    text: '#fff'

analytics:
  google:
    code: 'UA-48605964-34' # Change this to your GSA analytics code
  dap:
    agency: GSA    # Change this to your agency
    subagency: 18F # Change this to your agency

forms:
- type: newsletter
  heading: Sign up to receive updates about cloud.gov from 18F
  url: https://docs.google.com/forms/d/1S8P20K7yFTMAnpG9FT5r7aW5ja_phVcRqJbRlJqvqjM/formResponse
  button: Subscribe
  privacypolicy: Your privacy and security are important to us, we'll only share your information as described in the <a href="http://www.gsa.gov/portal/content/116609">GSA Privacy and Security Notice</a>
  fields:
    - type: email
      name: entry.1196036667
      label: Email Address
    - type: hidden
      name: fbzx
      value: -7237923910070247354

footer:
  email: cloud-gov-support@gsa.gov
  twitter:
    - 18f

# Build settings
markdown: kramdown
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md